/**
 * DGII's official provincia/municipio/distrito-municipal code catalog
 * (ProvinciaMunicipioType in the e-CF XSDs). Static national reference
 * data, not a database table -- it never changes at runtime and nobody
 * edits it. Extracted from e-cf/xsd/e-CF 31 v.1.0 (1).xsd's
 * ProvinciaMunicipioType enumeration.
 */

export type NivelDivisionTerritorial =
  'PROVINCIA' | 'MUNICIPIO' | 'DISTRITO_MUNICIPAL';

export interface DivisionTerritorial {
  codigo: string;
  nombre: string;
  nivel: NivelDivisionTerritorial;
}

export const DIVISIONES_TERRITORIALES: DivisionTerritorial[] = [
  { codigo: '010000', nombre: 'DISTRITO NACIONAL', nivel: 'PROVINCIA' },
  {
    codigo: '010100',
    nombre: 'MUNICIPIO SANTO DOMINGO DE GUZMÁN',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '010101',
    nombre: 'SANTO DOMINGO DE GUZMÁN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '020000', nombre: 'PROVINCIA AZUA', nivel: 'PROVINCIA' },
  { codigo: '020100', nombre: 'MUNICIPIO AZUA', nivel: 'MUNICIPIO' },
  { codigo: '020101', nombre: 'AZUA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '020102',
    nombre: 'BARRO ARRIBA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020103',
    nombre: 'LAS BARÍAS-LA ESTANCIA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020104',
    nombre: 'LOS JOVILLOS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020105',
    nombre: 'PUERTO VIEJO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020106',
    nombre: 'BARRERAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020107',
    nombre: 'DOÑA EMMA BALAGUER VIUDA VALLEJO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020108',
    nombre: 'CLAVELLINA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020109',
    nombre: 'LAS LOMAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '020200', nombre: 'MUNICIPIO LAS CHARCAS', nivel: 'MUNICIPIO' },
  {
    codigo: '020201',
    nombre: 'LAS CHARCAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020202',
    nombre: 'PALMAR DE OCOA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020300',
    nombre: 'MUNICIPIO LAS YAYAS DE VIAJAMA',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '020301',
    nombre: 'LAS YAYAS DE VIAJAMA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020302',
    nombre: 'VILLARPANDO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020303',
    nombre: 'HATO NUEVO CORTÉS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '020400', nombre: 'MUNICIPIO PADRE LAS CASAS', nivel: 'MUNICIPIO' },
  {
    codigo: '020401',
    nombre: 'PADRE LAS CASAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020402',
    nombre: 'LAS LAGUNAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020403',
    nombre: 'LA SIEMBRA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020404',
    nombre: 'MONTE BONITO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020405',
    nombre: 'LOS FRÍOS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '020500', nombre: 'MUNICIPIO PERALTA', nivel: 'MUNICIPIO' },
  { codigo: '020501', nombre: 'PERALTA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '020600', nombre: 'MUNICIPIO SABANA YEGUA', nivel: 'MUNICIPIO' },
  {
    codigo: '020601',
    nombre: 'SABANA YEGUA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020602',
    nombre: 'PROYECTO 4 (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020603',
    nombre: 'GANADERO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020604',
    nombre: 'PROYECTO 2-C (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '020700', nombre: 'MUNICIPIO PUEBLO VIEJO', nivel: 'MUNICIPIO' },
  {
    codigo: '020701',
    nombre: 'PUEBLO VIEJO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020702',
    nombre: 'EL ROSARIO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '020800', nombre: 'MUNICIPIO TÁBARA ARRIBA', nivel: 'MUNICIPIO' },
  {
    codigo: '020801',
    nombre: 'TÁBARA ARRIBA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020802',
    nombre: 'TÁBARA ABAJO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020803',
    nombre: 'AMIAMA GÓMEZ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '020804',
    nombre: 'LOS TOROS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '020900', nombre: 'MUNICIPIO GUAYABAL', nivel: 'MUNICIPIO' },
  {
    codigo: '020901',
    nombre: 'GUAYABAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '021000', nombre: 'MUNICIPIO ESTEBANÍA', nivel: 'MUNICIPIO' },
  {
    codigo: '021001',
    nombre: 'ESTEBANÍA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '030000', nombre: 'PROVINCIA BAHORUCO', nivel: 'PROVINCIA' },
  { codigo: '030001', nombre: 'MUNICIPIO NEIBA', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '030101', nombre: 'NEIBA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '030102',
    nombre: 'EL PALMAR (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '030200', nombre: 'MUNICIPIO GALVÁN', nivel: 'MUNICIPIO' },
  { codigo: '030201', nombre: 'GALVÁN (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '030202',
    nombre: 'EL SALADO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '030300', nombre: 'MUNICIPIO TAMAYO', nivel: 'MUNICIPIO' },
  { codigo: '030301', nombre: 'TAMAYO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '030302', nombre: 'UVILLA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '030303', nombre: 'SANTANA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '030304',
    nombre: 'MONSERRATE (MONTSERRAT) (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '030305',
    nombre: 'CABEZA DE TORO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '030306', nombre: 'MENA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '030307',
    nombre: 'SANTA BÁRBARA EL 6 (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '030400', nombre: 'MUNICIPIO VILLA JARAGUA', nivel: 'MUNICIPIO' },
  {
    codigo: '030401',
    nombre: 'VILLA JARAGUA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '030500', nombre: 'MUNICIPIO LOS RÍOS', nivel: 'MUNICIPIO' },
  {
    codigo: '030501',
    nombre: 'LOS RÍOS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '030502',
    nombre: 'LAS CLAVELLINAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '040000', nombre: 'PROVINCIA BARAHONA', nivel: 'PROVINCIA' },
  { codigo: '040100', nombre: 'MUNICIPIO BARAHONA', nivel: 'MUNICIPIO' },
  {
    codigo: '040101',
    nombre: 'BARAHONA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '040102',
    nombre: 'EL CACHÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '040103',
    nombre: 'LA GUÁZARA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '040104',
    nombre: 'VILLA CENTRAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '040200', nombre: 'MUNICIPIO CABRAL', nivel: 'MUNICIPIO' },
  { codigo: '040201', nombre: 'CABRAL (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '040300', nombre: 'MUNICIPIO ENRIQUILLO', nivel: 'MUNICIPIO' },
  {
    codigo: '040301',
    nombre: 'ENRIQUILLO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '040302',
    nombre: 'ARROYO DULCE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '040400', nombre: 'MUNICIPIO PARAÍSO', nivel: 'MUNICIPIO' },
  { codigo: '040401', nombre: 'PARAÍSO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '040402',
    nombre: 'LOS PATOS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '040500', nombre: 'MUNICIPIO VICENTE NOBLE', nivel: 'MUNICIPIO' },
  {
    codigo: '040501',
    nombre: 'VICENTE NOBLE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '040502', nombre: 'CANOA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '040503',
    nombre: 'QUITA CORAZA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '040504',
    nombre: 'FONDO NEGRO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '040600', nombre: 'MUNICIPIO EL PEÑÓN', nivel: 'MUNICIPIO' },
  {
    codigo: '040601',
    nombre: 'EL PEÑÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '040700', nombre: 'MUNICIPIO LA CIÉNAGA', nivel: 'MUNICIPIO' },
  {
    codigo: '040701',
    nombre: 'LA CIÉNAGA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '040702',
    nombre: 'BAHORUCO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '040800', nombre: 'MUNICIPIO FUNDACIÓN', nivel: 'MUNICIPIO' },
  {
    codigo: '040801',
    nombre: 'FUNDACIÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '040802',
    nombre: 'PESCADERÍA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '040900', nombre: 'MUNICIPIO LAS SALINAS', nivel: 'MUNICIPIO' },
  {
    codigo: '040901',
    nombre: 'LAS SALINAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '041000', nombre: 'MUNICIPIO POLO', nivel: 'MUNICIPIO' },
  { codigo: '041001', nombre: 'POLO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '041100', nombre: 'MUNICIPIO JAQUIMEYES', nivel: 'MUNICIPIO' },
  {
    codigo: '041101',
    nombre: 'JAQUIMEYES (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '041102',
    nombre: 'PALO ALTO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '050000', nombre: 'PROVINCIA DAJABÓN', nivel: 'PROVINCIA' },
  { codigo: '050100', nombre: 'MUNICIPIO DAJABÓN', nivel: 'MUNICIPIO' },
  { codigo: '050101', nombre: 'DAJABÓN (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '050102', nombre: 'CAÑONGO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '050200', nombre: 'MUNICIPIO LOMA DE CABRERA', nivel: 'MUNICIPIO' },
  {
    codigo: '050201',
    nombre: 'LOMA DE CABRERA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '050202',
    nombre: 'CAPOTILLO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '050203',
    nombre: 'SANTIAGO DE LA CRUZ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '050300', nombre: 'MUNICIPIO PARTIDO', nivel: 'MUNICIPIO' },
  { codigo: '050301', nombre: 'PARTIDO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '050400', nombre: 'MUNICIPIO RESTAURACIÓN', nivel: 'MUNICIPIO' },
  {
    codigo: '050401',
    nombre: 'RESTAURACIÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '050500', nombre: 'MUNICIPIO EL PINO', nivel: 'MUNICIPIO' },
  { codigo: '050501', nombre: 'EL PINO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '050502',
    nombre: 'MANUEL BUENO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '060000', nombre: 'PROVINCIA DUARTE', nivel: 'PROVINCIA' },
  {
    codigo: '060100',
    nombre: 'MUNICIPIO SAN FRANCISCO DE MACORÍS',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '060101',
    nombre: 'SAN FRANCISCO DE MACORÍS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '060102', nombre: 'LA PEÑA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '060103', nombre: 'CENOVÍ (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '060104', nombre: 'JAYA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '060105',
    nombre: 'PRESIDENTE DON ANTONIO GUZMÁN FERNÁNDEZ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '060200', nombre: 'MUNICIPIO ARENOSO', nivel: 'MUNICIPIO' },
  { codigo: '060201', nombre: 'ARENOSO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '060202',
    nombre: 'LAS COLES (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '060203',
    nombre: 'EL AGUACATE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '060300', nombre: 'MUNICIPIO CASTILLO', nivel: 'MUNICIPIO' },
  {
    codigo: '060301',
    nombre: 'CASTILLO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '060400', nombre: 'MUNICIPIO PIMENTEL', nivel: 'MUNICIPIO' },
  {
    codigo: '060401',
    nombre: 'PIMENTEL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '060500', nombre: 'MUNICIPIO VILLA RIVA', nivel: 'MUNICIPIO' },
  {
    codigo: '060501',
    nombre: 'VILLA RIVA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '060502',
    nombre: 'AGUA SANTA DEL YUNA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '060503',
    nombre: 'CRISTO REY DE GUARAGUAO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '060504',
    nombre: 'LAS TARANAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '060505',
    nombre: 'BARRAQUITO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '060600', nombre: 'MUNICIPIO LAS GUÁRANAS', nivel: 'MUNICIPIO' },
  {
    codigo: '060601',
    nombre: 'LAS GUÁRANAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '060700',
    nombre: 'MUNICIPIO EUGENIO MARÍA DE HOSTOS',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '060701',
    nombre: 'EUGENIO MARÍA DE HOSTOS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '060702',
    nombre: 'SABANA GRANDE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '070000', nombre: 'PROVINCIA ELÍAS PIÑA', nivel: 'PROVINCIA' },
  { codigo: '070100', nombre: 'MUNICIPIO COMENDADOR', nivel: 'MUNICIPIO' },
  {
    codigo: '070101',
    nombre: 'COMENDADOR (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '070102',
    nombre: 'SABANA LARGA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '070103', nombre: 'GUAYABO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '070200', nombre: 'MUNICIPIO BÁNICA', nivel: 'MUNICIPIO' },
  { codigo: '070201', nombre: 'BÁNICA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '070202',
    nombre: 'SABANA CRUZ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '070203',
    nombre: 'SABANA HIGÜERO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '070300', nombre: 'MUNICIPIO EL LLANO', nivel: 'MUNICIPIO' },
  {
    codigo: '070301',
    nombre: 'EL LLANO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '070302', nombre: 'GUANITO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '070400', nombre: 'MUNICIPIO HONDO VALLE', nivel: 'MUNICIPIO' },
  {
    codigo: '070401',
    nombre: 'HONDO VALLE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '070402',
    nombre: 'RANCHO DE LA GUARDIA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '070500', nombre: 'MUNICIPIO PEDRO SANTANA', nivel: 'MUNICIPIO' },
  {
    codigo: '070501',
    nombre: 'PEDRO SANTANA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '070502',
    nombre: 'RÍO LIMPIO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '070600', nombre: 'MUNICIPIO JUAN SANTIAGO', nivel: 'MUNICIPIO' },
  {
    codigo: '070601',
    nombre: 'JUAN SANTIAGO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '080000', nombre: 'PROVINCIA EL SEIBO', nivel: 'PROVINCIA' },
  { codigo: '080100', nombre: 'MUNICIPIO EL SEIBO', nivel: 'MUNICIPIO' },
  {
    codigo: '080101',
    nombre: 'EL SEIBO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '080102',
    nombre: 'PEDRO SÁNCHEZ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '080103',
    nombre: 'SAN FRANCISCO-VICENTILLO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '080104',
    nombre: 'SANTA LUCÍA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '080200', nombre: 'MUNICIPIO MICHES', nivel: 'MUNICIPIO' },
  { codigo: '080201', nombre: 'MICHES (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '080202',
    nombre: 'EL CEDRO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '080203', nombre: 'LA GINA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '090000', nombre: 'PROVINCIA ESPAILLAT', nivel: 'PROVINCIA' },
  { codigo: '090100', nombre: 'MUNICIPIO MOCA', nivel: 'MUNICIPIO' },
  { codigo: '090101', nombre: 'MOCA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '090102',
    nombre: 'JOSÉ CONTRERAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '090103',
    nombre: 'SAN VÍCTOR (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '090104',
    nombre: 'JUAN LÓPEZ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '090105',
    nombre: 'LAS LAGUNAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '090106',
    nombre: 'CANCA LA REYNA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '090107',
    nombre: 'EL HIGÜERITO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '090108',
    nombre: 'MONTE DE LA JAGUA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '090109',
    nombre: 'LA ORTEGA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '090200',
    nombre: 'MUNICIPIO CAYETANO GERMOSÉN',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '090201',
    nombre: 'CAYETANO GERMOSÉN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '090300',
    nombre: 'MUNICIPIO GASPAR HERNÁNDEZ',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '090301',
    nombre: 'GASPAR HERNÁNDEZ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '090302',
    nombre: 'JOBA ARRIBA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '090303', nombre: 'VERAGUA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '090304',
    nombre: 'VILLA MAGANTE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '090400', nombre: 'MUNICIPIO JAMAO AL NORTE', nivel: 'MUNICIPIO' },
  {
    codigo: '090401',
    nombre: 'JAMAO AL NORTE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '100000', nombre: 'PROVINCIA INDEPENDENCIA', nivel: 'PROVINCIA' },
  { codigo: '100100', nombre: 'MUNICIPIO JIMANÍ', nivel: 'MUNICIPIO' },
  { codigo: '100101', nombre: 'JIMANÍ (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '100102',
    nombre: 'EL LIMÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '100103',
    nombre: 'BOCA DE CACHÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '100200', nombre: 'MUNICIPIO DUVERGÉ', nivel: 'MUNICIPIO' },
  { codigo: '100201', nombre: 'DUVERGÉ (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '100202',
    nombre: 'VENGAN A VER (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '100300', nombre: 'MUNICIPIO LA DESCUBIERTA', nivel: 'MUNICIPIO' },
  {
    codigo: '100301',
    nombre: 'LA DESCUBIERTA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '100400', nombre: 'MUNICIPIO POSTRER RÍO', nivel: 'MUNICIPIO' },
  {
    codigo: '100401',
    nombre: 'POSTRER RÍO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '100402',
    nombre: 'GUAYABAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '100500', nombre: 'MUNICIPIO CRISTÓBAL', nivel: 'MUNICIPIO' },
  {
    codigo: '100501',
    nombre: 'CRISTÓBAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '100502', nombre: 'BATEY 8 (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '100600', nombre: 'MUNICIPIO MELLA', nivel: 'MUNICIPIO' },
  { codigo: '100601', nombre: 'MELLA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '100602',
    nombre: 'LA COLONIA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '110000', nombre: 'PROVINCIA LA ALTAGRACIA', nivel: 'PROVINCIA' },
  { codigo: '110100', nombre: 'MUNICIPIO HIGÜEY', nivel: 'MUNICIPIO' },
  { codigo: '110101', nombre: 'HIGÜEY (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '110102',
    nombre: 'LAS LAGUNAS DE NISIBÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '110103',
    nombre: 'LA OTRA BANDA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '110104',
    nombre: 'VERÓN PUNTA CANA (D. M.) (Incluye Bávaro)',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '110200',
    nombre: 'MUNICIPIO SAN RAFAEL DEL YUMA',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '110201',
    nombre: 'SAN RAFAEL DEL YUMA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '110202',
    nombre: 'BOCA DE YUMA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '110203',
    nombre: 'BAYAHÍBE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '120000', nombre: 'PROVINCIA LA ROMANA', nivel: 'PROVINCIA' },
  { codigo: '120100', nombre: 'MUNICIPIO LA ROMANA', nivel: 'MUNICIPIO' },
  {
    codigo: '120101',
    nombre: 'LA ROMANA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '120102', nombre: 'CALETA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '120200', nombre: 'MUNICIPIO GUAYMATE', nivel: 'MUNICIPIO' },
  {
    codigo: '120201',
    nombre: 'GUAYMATE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '120300', nombre: 'MUNICIPIO VILLA HERMOSA', nivel: 'MUNICIPIO' },
  {
    codigo: '120301',
    nombre: 'VILLA HERMOSA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '120302',
    nombre: 'CUMAYASA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '130000', nombre: 'PROVINCIA LA VEGA', nivel: 'PROVINCIA' },
  { codigo: '130100', nombre: 'MUNICIPIO LA VEGA', nivel: 'MUNICIPIO' },
  { codigo: '130101', nombre: 'LA VEGA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '130102',
    nombre: 'RÍO VERDE ARRIBA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '130103',
    nombre: 'EL RANCHITO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '130104', nombre: 'TAVERAS (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '130105',
    nombre: 'DON JUAN RODRÍGUEZ (D.M.)',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '130200', nombre: 'MUNICIPIO CONSTANZA', nivel: 'MUNICIPIO' },
  {
    codigo: '130201',
    nombre: 'CONSTANZA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '130202', nombre: 'TIREO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '130203',
    nombre: 'LA SABINA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '130300', nombre: 'MUNICIPIO JARABACOA', nivel: 'MUNICIPIO' },
  {
    codigo: '130301',
    nombre: 'JARABACOA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '130302',
    nombre: 'BUENA VISTA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '130303', nombre: 'MANABAO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '130400', nombre: 'MUNICIPIO JIMA ABAJO', nivel: 'MUNICIPIO' },
  {
    codigo: '130401',
    nombre: 'JIMA ABAJO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '130402', nombre: 'RINCÓN (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '140000',
    nombre: 'PROVINCIA MARÍA TRINIDAD SÁNCHEZ',
    nivel: 'PROVINCIA',
  },
  { codigo: '140100', nombre: 'MUNICIPIO NAGUA', nivel: 'MUNICIPIO' },
  { codigo: '140101', nombre: 'NAGUA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '140102',
    nombre: 'SAN JOSÉ DE MATANZAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '140103',
    nombre: 'LAS GORDAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '140104',
    nombre: 'ARROYO AL MEDIO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '140200', nombre: 'MUNICIPIO CABRERA', nivel: 'MUNICIPIO' },
  { codigo: '140201', nombre: 'CABRERA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '140202',
    nombre: 'ARROYO SALADO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '140203',
    nombre: 'LA ENTRADA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '140300', nombre: 'MUNICIPIO EL FACTOR', nivel: 'MUNICIPIO' },
  {
    codigo: '140301',
    nombre: 'EL FACTOR (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '140302', nombre: 'EL POZO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '140400', nombre: 'MUNICIPIO RÍO SAN JUAN', nivel: 'MUNICIPIO' },
  {
    codigo: '140401',
    nombre: 'RÍO SAN JUAN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '150000', nombre: 'PROVINCIA MONTE CRISTI', nivel: 'PROVINCIA' },
  { codigo: '150100', nombre: 'MUNICIPIO MONTE CRISTI', nivel: 'MUNICIPIO' },
  {
    codigo: '150101',
    nombre: 'MONTE CRISTI (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '150200', nombre: 'MUNICIPIO CASTAÑUELAS', nivel: 'MUNICIPIO' },
  {
    codigo: '150201',
    nombre: 'CASTAÑUELAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '150202',
    nombre: 'PALO VERDE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '150300', nombre: 'MUNICIPIO GUAYUBÍN', nivel: 'MUNICIPIO' },
  {
    codigo: '150301',
    nombre: 'GUAYUBÍN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '150302',
    nombre: 'VILLA ELISA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '150303',
    nombre: 'HATILLO PALMA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '150304',
    nombre: 'CANA CHAPETÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '150400',
    nombre: 'MUNICIPIO LAS MATAS DE SANTA CRUZ',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '150401',
    nombre: 'LAS MATAS DE SANTA CRUZ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '150500', nombre: 'MUNICIPIO PEPILLO SALCEDO', nivel: 'MUNICIPIO' },
  {
    codigo: '150501',
    nombre: 'PEPILLO SALCEDO (MANZANILLO)',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '150502',
    nombre: 'SANTA MARÍA (D. M.)',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '150600', nombre: 'MUNICIPIO VILLA VÁSQUEZ', nivel: 'MUNICIPIO' },
  { codigo: '150601', nombre: 'VILLA VÁSQUEZ', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '160000', nombre: 'PROVINCIA PEDERNALES', nivel: 'PROVINCIA' },
  { codigo: '160100', nombre: 'MUNICIPIO PEDERNALES', nivel: 'MUNICIPIO' },
  { codigo: '160101', nombre: 'PEDERNALES', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '160102',
    nombre: 'JOSÉ FRANCISCO PEÑA GÓMEZ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '160200', nombre: 'MUNICIPIO OVIEDO', nivel: 'MUNICIPIO' },
  { codigo: '160201', nombre: 'OVIEDO', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '160202', nombre: 'JUANCHO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '170000', nombre: 'PROVINCIA PERAVIA', nivel: 'PROVINCIA' },
  { codigo: '170100', nombre: 'MUNICIPIO BANÍ', nivel: 'MUNICIPIO' },
  { codigo: '170101', nombre: 'BANÍ (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '170102',
    nombre: 'MATANZAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '170103',
    nombre: 'VILLA FUNDACIÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '170104',
    nombre: 'SABANA BUEY (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '170105', nombre: 'PAYA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '170106',
    nombre: 'VILLA SOMBRERO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '170107',
    nombre: 'EL CARRETÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '170108',
    nombre: 'CATALINA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '170109',
    nombre: 'EL LIMONAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '170110',
    nombre: 'LAS BARÍAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '170200', nombre: 'MUNICIPIO NIZAO', nivel: 'MUNICIPIO' },
  { codigo: '170201', nombre: 'NIZAO', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '170202',
    nombre: 'PIZARRETE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '170203', nombre: 'SANTANA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '170300', nombre: 'MATANZAS', nivel: 'MUNICIPIO' },
  { codigo: '170301', nombre: 'MATANZAS', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '180000', nombre: 'PROVINCIA PUERTO PLATA', nivel: 'PROVINCIA' },
  { codigo: '180100', nombre: 'MUNICIPIO PUERTO PLATA', nivel: 'MUNICIPIO' },
  {
    codigo: '180101',
    nombre: 'PUERTO PLATA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '180102',
    nombre: 'YÁSICA ARRIBA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '180103', nombre: 'MAIMÓN (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '180200', nombre: 'MUNICIPIO ALTAMIRA', nivel: 'MUNICIPIO' },
  { codigo: '180201', nombre: 'ALTAMIRA', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '180202',
    nombre: 'RÍO GRANDE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '180300', nombre: 'MUNICIPIO GUANANICO', nivel: 'MUNICIPIO' },
  { codigo: '180301', nombre: 'GUANANICO', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '180400', nombre: 'MUNICIPIO IMBERT', nivel: 'MUNICIPIO' },
  { codigo: '180401', nombre: 'IMBERT', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '180500', nombre: 'MUNICIPIO LOS HIDALGOS', nivel: 'MUNICIPIO' },
  { codigo: '180501', nombre: 'LOS HIDALGOS', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '180502', nombre: 'NAVAS (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '180600', nombre: 'MUNICIPIO LUPERÓN', nivel: 'MUNICIPIO' },
  { codigo: '180601', nombre: 'LUPERÓN', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '180602',
    nombre: 'LA ISABELA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '180603', nombre: 'BELLOSO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '180604',
    nombre: 'EL ESTRECHO DE LUPERÓN OMAR BROSS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '180700', nombre: 'MUNICIPIO SOSÚA', nivel: 'MUNICIPIO' },
  { codigo: '180701', nombre: 'SOSÚA', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '180702',
    nombre: 'CABARETE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '180703',
    nombre: 'SABANETA DE YÁSICA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '180800', nombre: 'MUNICIPIO VILLA ISABELA', nivel: 'MUNICIPIO' },
  { codigo: '180801', nombre: 'VILLA ISABELA', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '180802',
    nombre: 'ESTERO HONDO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '180803',
    nombre: 'LA JAIBA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '180804', nombre: 'GUALETE (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '180900',
    nombre: 'MUNICIPIO VILLA MONTELLANO',
    nivel: 'MUNICIPIO',
  },
  { codigo: '180901', nombre: 'VILLA MONTELLANO', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '190000',
    nombre: 'PROVINCIA HERMANAS MIRABAL',
    nivel: 'PROVINCIA',
  },
  { codigo: '190100', nombre: 'MUNICIPIO SALCEDO', nivel: 'MUNICIPIO' },
  { codigo: '190101', nombre: 'SALCEDO', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '190102',
    nombre: 'JAMAO AFUERA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '190200', nombre: 'MUNICIPIO TENARES', nivel: 'MUNICIPIO' },
  { codigo: '190201', nombre: 'TENARES', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '190202', nombre: 'BLANCO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '190300', nombre: 'MUNICIPIO VILLA TAPIA', nivel: 'MUNICIPIO' },
  { codigo: '190301', nombre: 'VILLA TAPIA', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '200000', nombre: 'PROVINCIA SAMANÁ', nivel: 'PROVINCIA' },
  { codigo: '200100', nombre: 'MUNICIPIO SAMANÁ', nivel: 'MUNICIPIO' },
  { codigo: '200101', nombre: 'SAMANÁ', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '200102',
    nombre: 'EL LIMÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '200103',
    nombre: 'ARROYO BARRIL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '200104',
    nombre: 'LAS GALERAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '200200', nombre: 'MUNICIPIO SÁNCHEZ', nivel: 'MUNICIPIO' },
  { codigo: '200201', nombre: 'SÁNCHEZ (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '200300', nombre: 'MUNICIPIO LAS TERRENAS', nivel: 'MUNICIPIO' },
  { codigo: '200301', nombre: 'LAS TERRENAS', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '210000', nombre: 'PROVINCIA SAN CRISTÓBAL', nivel: 'PROVINCIA' },
  { codigo: '210100', nombre: 'MUNICIPIO SAN CRISTÓBAL', nivel: 'MUNICIPIO' },
  {
    codigo: '210101',
    nombre: 'SAN CRISTÓBAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '210102',
    nombre: 'HATO DAMAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '210103', nombre: 'HATILLO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '210200',
    nombre: 'MUNICIPIO SABANA GRANDE DE PALENQUE',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '210201',
    nombre: 'SABANA GRANDE DE PALENQUE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '210300', nombre: 'MUNICIPIO BAJOS DE HAINA', nivel: 'MUNICIPIO' },
  { codigo: '210301', nombre: 'BAJOS DE HAINA', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '210302',
    nombre: 'EL CARRIL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '210303',
    nombre: 'QUITA SUEÑO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '210400',
    nombre: 'MUNICIPIO CAMBITA GARABITOS',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '210401',
    nombre: 'CAMBITA GARABITOS',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '210402',
    nombre: 'CAMBITA EL PUEBLECITO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '210500',
    nombre: 'MUNICIPIO VILLA ALTAGRACIA',
    nivel: 'MUNICIPIO',
  },
  { codigo: '210501', nombre: 'VILLA ALTAGRACIA', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '210502',
    nombre: 'SAN JOSÉ DEL PUERTO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '210503', nombre: 'MEDINA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '210504',
    nombre: 'LA CUCHILLA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '210600', nombre: 'MUNICIPIO YAGUATE', nivel: 'MUNICIPIO' },
  { codigo: '210601', nombre: 'YAGUATE (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '210602', nombre: 'DOÑA ANA (D. M.)', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '210700',
    nombre: 'MUNICIPIO SAN GREGORIO DE NIGUA',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '210701',
    nombre: 'SAN GREGORIO DE NIGUA',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '210800', nombre: 'MUNICIPIO LOS CACAOS', nivel: 'MUNICIPIO' },
  {
    codigo: '210801',
    nombre: 'LOS CACAOS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '220000', nombre: 'PROVINCIA SAN JUAN', nivel: 'PROVINCIA' },
  { codigo: '220100', nombre: 'MUNICIPIO SAN JUAN', nivel: 'MUNICIPIO' },
  { codigo: '220101', nombre: 'SAN JUAN', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '220102',
    nombre: 'PEDRO CORTO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '220103',
    nombre: 'SABANETA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '220104',
    nombre: 'SABANA ALTA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '220105',
    nombre: 'EL ROSARIO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '220106',
    nombre: 'HATO DEL PADRE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '220107', nombre: 'GUANITO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '220108',
    nombre: 'LA JAGUA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '220109',
    nombre: 'LAS MAGUANAS-HATO NUEVO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '220110',
    nombre: 'LAS CHARCAS DE MARÍA NOVA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '220111',
    nombre: 'LAS ZANJAS (D. M.)',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '220200', nombre: 'MUNICIPIO BOHECHÍO', nivel: 'MUNICIPIO' },
  { codigo: '220201', nombre: 'BOHECHÍO', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '220202',
    nombre: 'ARROYO CANO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '220203', nombre: 'YAQUE (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '220300', nombre: 'MUNICIPIO EL CERCADO', nivel: 'MUNICIPIO' },
  { codigo: '220301', nombre: 'EL CERCADO', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '220302',
    nombre: 'DERRUMBADERO (D. M.)',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '220303', nombre: 'BATISTA (D. M.)', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '220400', nombre: 'MUNICIPIO JUAN DE HERRERA', nivel: 'MUNICIPIO' },
  { codigo: '220401', nombre: 'JUAN DE HERRERA', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '220402', nombre: 'JÍNOVA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '220500',
    nombre: 'MUNICIPIO LAS MATAS DE FARFÁN',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '220501',
    nombre: 'LAS MATAS DE FARFÁN',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '220502',
    nombre: 'MATAYAYA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '220503',
    nombre: 'CARRERA DE YEGUAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '220600', nombre: 'MUNICIPIO VALLEJUELO', nivel: 'MUNICIPIO' },
  { codigo: '220601', nombre: 'VALLEJUELO', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '220602',
    nombre: 'JORJILLO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '230000',
    nombre: 'PROVINCIA SAN PEDRO DE MACORÍS',
    nivel: 'PROVINCIA',
  },
  {
    codigo: '230100',
    nombre: 'MUNICIPIO SAN PEDRO DE MACORÍS',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '230101',
    nombre: 'SAN PEDRO DE MACORÍS',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '230200', nombre: 'MUNICIPIO LOS LLANOS', nivel: 'MUNICIPIO' },
  { codigo: '230201', nombre: 'LOS LLANOS', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '230202',
    nombre: 'EL PUERTO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '230203', nombre: 'GAUTIER (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '230300', nombre: 'MUNICIPIO RAMÓN SANTANA', nivel: 'MUNICIPIO' },
  { codigo: '230301', nombre: 'RAMÓN SANTANA', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '230400', nombre: 'MUNICIPIO CONSUELO', nivel: 'MUNICIPIO' },
  { codigo: '230401', nombre: 'CONSUELO', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '230500', nombre: 'MUNICIPIO QUISQUEYA', nivel: 'MUNICIPIO' },
  { codigo: '230501', nombre: 'QUISQUEYA', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '230600', nombre: 'MUNICIPIO GUAYACANES', nivel: 'MUNICIPIO' },
  { codigo: '230601', nombre: 'GUAYACANES', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '240000', nombre: 'PROVINCIA SANCHEZ RAMÍREZ', nivel: 'PROVINCIA' },
  { codigo: '240100', nombre: 'MUNICIPIO COTUÍ', nivel: 'MUNICIPIO' },
  { codigo: '240101', nombre: 'COTUÍ', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '240102',
    nombre: 'QUITA SUEÑO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '240103',
    nombre: 'CABALLERO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '240104',
    nombre: 'COMEDERO ARRIBA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '240105',
    nombre: 'PLATANAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '240106', nombre: 'ZAMBRANA ABAJO', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '240200', nombre: 'MUNICIPIO CEVICOS', nivel: 'MUNICIPIO' },
  { codigo: '240201', nombre: 'CEVICOS', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '240202',
    nombre: 'LA CUEVA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '240300', nombre: 'MUNICIPIO FANTINO', nivel: 'MUNICIPIO' },
  { codigo: '240301', nombre: 'FANTINO', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '240400', nombre: 'MUNICIPIO LA MATA', nivel: 'MUNICIPIO' },
  { codigo: '240401', nombre: 'LA MATA', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '240402', nombre: 'LA BIJA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '240403',
    nombre: 'ANGELINA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '240404',
    nombre: 'HERNANDO ALONZO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '250000', nombre: 'PROVINCIA SANTIAGO', nivel: 'PROVINCIA' },
  { codigo: '250100', nombre: 'MUNICIPIO SANTIAGO', nivel: 'MUNICIPIO' },
  { codigo: '250101', nombre: 'SANTIAGO', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '250102',
    nombre: 'PEDRO GARCÍA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '250104', nombre: 'BAITOA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '250105',
    nombre: 'LA CANELA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '250106',
    nombre: 'SAN FRANCISCO DE JACAGUA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '250107',
    nombre: 'HATO DEL YAQUE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '250200', nombre: 'MUNICIPIO BISONÓ', nivel: 'MUNICIPIO' },
  {
    codigo: '250201',
    nombre: 'VILLA BISONÓ (NAVARRETE) (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '250300', nombre: 'MUNICIPIO JÁNICO', nivel: 'MUNICIPIO' },
  { codigo: '250301', nombre: 'JÁNICO', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '250302',
    nombre: 'JUNCALITO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '250303',
    nombre: 'EL CAIMITO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '250400', nombre: 'MUNICIPIO LICEY AL MEDIO', nivel: 'MUNICIPIO' },
  { codigo: '250401', nombre: 'LICEY AL MEDIO', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '250402',
    nombre: 'LAS PALOMAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '250500',
    nombre: 'MUNICIPIO SAN JOSÉ DE LAS MATAS',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '250501',
    nombre: 'SAN JOSÉ DE LAS MATAS',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '250502',
    nombre: 'EL RUBIO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '250503',
    nombre: 'LA CUESTA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '250504',
    nombre: 'LAS PLACETAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '250600', nombre: 'MUNICIPIO TAMBORIL', nivel: 'MUNICIPIO' },
  { codigo: '250601', nombre: 'TAMBORIL', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '250602',
    nombre: 'CANCA LA PIEDRA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '250700', nombre: 'MUNICIPIO VILLA GONZÁLEZ', nivel: 'MUNICIPIO' },
  { codigo: '250701', nombre: 'VILLA GONZÁLEZ', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '250702',
    nombre: 'PALMAR ARRIBA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '250703',
    nombre: 'EL LIMÓN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '250800', nombre: 'MUNICIPIO PUÑAL', nivel: 'MUNICIPIO' },
  { codigo: '250801', nombre: 'PUÑAL', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '250802',
    nombre: 'GUAYABAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '250803',
    nombre: 'CANABACOA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '250900', nombre: 'MUNICIPIO SABANA IGLESIA', nivel: 'MUNICIPIO' },
  { codigo: '250901', nombre: 'SABANA IGLESIA', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '251000', nombre: 'BAITOA', nivel: 'MUNICIPIO' },
  { codigo: '251001', nombre: 'BAITOA', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '260000',
    nombre: 'PROVINCIA SANTIAGO RODRÍGUEZ',
    nivel: 'PROVINCIA',
  },
  {
    codigo: '260100',
    nombre: 'MUNICIPIO SAN IGNACIO DE SABANETA',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '260101',
    nombre: 'SAN IGNACIO DE SABANETA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '260200',
    nombre: 'MUNICIPIO VILLA LOS ALMÁCIGOS',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '260201',
    nombre: 'VILLA LOS ALMÁCIGOS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '260300', nombre: 'MUNICIPIO MONCIÓN', nivel: 'MUNICIPIO' },
  { codigo: '260301', nombre: 'MONCIÓN (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '270000', nombre: 'PROVINCIA VALVERDE', nivel: 'PROVINCIA' },
  { codigo: '270100', nombre: 'MUNICIPIO MAO', nivel: 'MUNICIPIO' },
  { codigo: '270101', nombre: 'MAO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '270102', nombre: 'AMINA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '270103',
    nombre: 'JAIBÓN (PUEBLO NUEVO) (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '270104',
    nombre: 'GUATAPANAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '270200', nombre: 'MUNICIPIO ESPERANZA', nivel: 'MUNICIPIO' },
  { codigo: '270201', nombre: 'ESPERANZA', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '270202', nombre: 'MAIZAL (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '270203', nombre: 'JICOMÉ (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '270204',
    nombre: 'BOCA DE MAO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '270205',
    nombre: 'PARADERO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '270300', nombre: 'MUNICIPIO LAGUNA SALADA', nivel: 'MUNICIPIO' },
  {
    codigo: '270301',
    nombre: 'LAGUNA SALADA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '270302', nombre: 'JAIBÓN (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '270303', nombre: 'LA CAYA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '270304',
    nombre: 'CRUCE DE GUAYACANES (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '280000', nombre: 'PROVINCIA MONSEÑOR NOUEL', nivel: 'PROVINCIA' },
  { codigo: '280100', nombre: 'MUNICIPIO BONAO', nivel: 'MUNICIPIO' },
  { codigo: '280101', nombre: 'BONAO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '280102',
    nombre: 'SABANA DEL PUERTO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '280103',
    nombre: 'JUMA BEJUCAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '280104',
    nombre: 'ARROYO TORO - MASIPEDRO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '280105', nombre: 'JAYACO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '280106',
    nombre: 'LA SALVIA - LOS QUEMADOS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '280200', nombre: 'MUNICIPIO MAIMÓN', nivel: 'MUNICIPIO' },
  { codigo: '280201', nombre: 'MAIMÓN (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '280300', nombre: 'MUNICIPIO PIEDRA BLANCA', nivel: 'MUNICIPIO' },
  {
    codigo: '280301',
    nombre: 'PIEDRA BLANCA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '280302',
    nombre: 'VILLA DE SONADOR (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '280303',
    nombre: 'JUAN ADRIÁN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '290000', nombre: 'PROVINCIA MONTE PLATA', nivel: 'PROVINCIA' },
  { codigo: '290100', nombre: 'MUNICIPIO MONTE PLATA', nivel: 'MUNICIPIO' },
  {
    codigo: '290101',
    nombre: 'MONTE PLATA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '290102',
    nombre: 'DON JUAN (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '290103', nombre: 'CHIRINO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '290104', nombre: 'BOYÁ (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '290200', nombre: 'MUNICIPIO BAYAGUANA', nivel: 'MUNICIPIO' },
  {
    codigo: '290201',
    nombre: 'BAYAGUANA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '290300',
    nombre: 'MUNICIPIO SABANA GRANDE DE BOYÁ',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '290301',
    nombre: 'SABANA GRANDE DE BOYÁ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '290302', nombre: 'GONZALO (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  {
    codigo: '290303',
    nombre: 'MAJAGUAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '290400', nombre: 'MUNICIPIO YAMASÁ', nivel: 'MUNICIPIO' },
  {
    codigo: '290402',
    nombre: 'LOS BOTADOS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '290403',
    nombre: 'MAMÁ TINGÓ (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '290500', nombre: 'MUNICIPIO PERALVILLO', nivel: 'MUNICIPIO' },
  {
    codigo: '290501',
    nombre: 'PERALVILLO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '300000', nombre: 'PROVINCIA HATO MAYOR', nivel: 'PROVINCIA' },
  { codigo: '300100', nombre: 'MUNICIPIO HATO MAYOR', nivel: 'MUNICIPIO' },
  {
    codigo: '300101',
    nombre: 'HATO MAYOR (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '300102',
    nombre: 'YERBA BUENA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '300103',
    nombre: 'MATA PALACIO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '300104',
    nombre: 'GUAYABO DULCE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '300200',
    nombre: 'MUNICIPIO SABANA DE LA MAR',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '300201',
    nombre: 'SABANA DE LA MAR (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '300202',
    nombre: 'ELUPINA CORDERO DE LAS CAÑITAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '300300', nombre: 'MUNICIPIO EL VALLE', nivel: 'MUNICIPIO' },
  {
    codigo: '300301',
    nombre: 'EL VALLE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '310000',
    nombre: 'PROVINCIA SAN JOSÉ DE OCOA',
    nivel: 'PROVINCIA',
  },
  {
    codigo: '310100',
    nombre: 'MUNICIPIO SAN JOSÉ DE OCOA',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '310101',
    nombre: 'SAN JOSÉ DE OCOA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '310102',
    nombre: 'LA CIÉNAGA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '310103',
    nombre: 'NIZAO - LAS AUYAMAS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '310104',
    nombre: 'EL PINAR (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '310105',
    nombre: 'EL NARANJAL (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '310200', nombre: 'MUNICIPIO SABANA LARGA', nivel: 'MUNICIPIO' },
  {
    codigo: '310201',
    nombre: 'SABANA LARGA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '310300', nombre: 'MUNICIPIO RANCHO ARRIBA', nivel: 'MUNICIPIO' },
  {
    codigo: '310301',
    nombre: 'RANCHO ARRIBA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '320000', nombre: 'PROVINCIA SANTO DOMINGO', nivel: 'PROVINCIA' },
  {
    codigo: '320100',
    nombre: 'MUNICIPIO SANTO DOMINGO ESTE',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '320101',
    nombre: 'SANTO DOMINGO ESTE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '320102',
    nombre: 'SAN LUIS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '320200',
    nombre: 'MUNICIPIO SANTO DOMINGO OESTE',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '320201',
    nombre: 'SANTO DOMINGO OESTE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '320300',
    nombre: 'MUNICIPIO SANTO DOMINGO NORTE',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '320301',
    nombre: 'SANTO DOMINGO NORTE (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '320302',
    nombre: 'LA VICTORIA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '320400', nombre: 'MUNICIPIO BOCA CHICA', nivel: 'MUNICIPIO' },
  {
    codigo: '320401',
    nombre: 'BOCA CHICA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '320402',
    nombre: 'LA CALETA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '320500',
    nombre: 'MUNICIPIO SAN ANTONIO DE GUERRA',
    nivel: 'MUNICIPIO',
  },
  {
    codigo: '320501',
    nombre: 'SAN ANTONIO DE GUERRA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '320502',
    nombre: 'HATO VIEJO (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '320600', nombre: 'MUNICIPIO LOS ALCARRIZOS', nivel: 'MUNICIPIO' },
  {
    codigo: '320601',
    nombre: 'LOS ALCARRIZOS (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '320602',
    nombre: 'PALMAREJO-VILLA LINDA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  { codigo: '320603', nombre: 'PANTOJA (D. M.).', nivel: 'DISTRITO_MUNICIPAL' },
  { codigo: '320700', nombre: 'MUNICIPIO PEDRO BRAND', nivel: 'MUNICIPIO' },
  {
    codigo: '320701',
    nombre: 'PEDRO BRAND (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '320702',
    nombre: 'LA GUÁYIGA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
  {
    codigo: '320703',
    nombre: 'LA CUABA (D. M.).',
    nivel: 'DISTRITO_MUNICIPAL',
  },
];

const CODIGOS_VALIDOS = new Set(DIVISIONES_TERRITORIALES.map((d) => d.codigo));

export function esCodigoDivisionTerritorialValido(codigo: string): boolean {
  return CODIGOS_VALIDOS.has(codigo);
}

function codigosPorNivel(nivel: NivelDivisionTerritorial): string[] {
  return DIVISIONES_TERRITORIALES.filter((d) => d.nivel === nivel).map(
    (d) => d.codigo,
  );
}

/** DGII's Emisor/Comprador "Provincia" field expects a provincia-level code. */
export const CODIGOS_PROVINCIA = codigosPorNivel('PROVINCIA');

/** DGII's Emisor/Comprador "Municipio" field expects a municipio-level code. */
export const CODIGOS_MUNICIPIO = codigosPorNivel('MUNICIPIO');
